FROM node:22.16.0-slim

RUN apt-get update && apt-get install -y git curl bash
RUN curl -LO https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN apt-get install -y ./google-chrome-stable_current_amd64.deb

WORKDIR /grafana

# CMD ["pa11y-ci", "--config", "pa11y.json", "http://localhost:3001/login"]

CMD ["/bin/bash"]