//
// Code generated by grafana-app-sdk. DO NOT EDIT.
//

package v0alpha1

import (
	"github.com/grafana/grafana-app-sdk/resource"
)

// schema is unexported to prevent accidental overwrites
var (
	schemaSetting = resource.NewSimpleSchema("settings.grafana.app", "v0alpha1", &Setting{}, &SettingList{}, resource.WithKind("Setting"),
		resource.WithPlural("settings"), resource.WithScope(resource.NamespacedScope))
	kindSetting = resource.Kind{
		Schema: schemaSetting,
		Codecs: map[resource.KindEncoding]resource.Codec{
			resource.KindEncodingJSON: &SettingJSONCodec{},
		},
	}
)

// Kind returns a resource.Kind for this Schema with a JSON codec
func SettingKind() resource.Kind {
	return kindSetting
}

// Schema returns a resource.SimpleSchema representation of Setting
func SettingSchema() *resource.SimpleSchema {
	return schemaSetting
}

// Interface compliance checks
var _ resource.Schema = kindSetting
