//
// Code generated by grafana-app-sdk. DO NOT EDIT.
//

package v0alpha1

import (
	"github.com/grafana/grafana-app-sdk/resource"
)

// schema is unexported to prevent accidental overwrites
var (
	schemaCollection = resource.NewSimpleSchema("collection.grafana.app", "v0alpha1", &Collection{}, &CollectionList{}, resource.WithKind("Collection"),
		resource.WithPlural("collections"), resource.WithScope(resource.NamespacedScope))
	kindCollection = resource.Kind{
		Schema: schemaCollection,
		Codecs: map[resource.KindEncoding]resource.Codec{
			resource.KindEncodingJSON: &CollectionJSONCodec{},
		},
	}
)

// Kind returns a resource.Kind for this Schema with a JSON codec
func CollectionKind() resource.Kind {
	return kindCollection
}

// Schema returns a resource.SimpleSchema representation of Collection
func CollectionSchema() *resource.SimpleSchema {
	return schemaCollection
}

// Interface compliance checks
var _ resource.Schema = kindCollection
