//
// Code generated by grafana-app-sdk. DO NOT EDIT.
//

package v0alpha1

import (
	"github.com/grafana/grafana-app-sdk/resource"
)

// schema is unexported to prevent accidental overwrites
var (
	schemaTeamPermission = resource.NewSimpleSchema("iam.grafana.app", "v0alpha1", &TeamPermission{}, &TeamPermissionList{}, resource.WithKind("TeamPermission"),
		resource.WithPlural("teampermissions"), resource.WithScope(resource.NamespacedScope))
	kindTeamPermission = resource.Kind{
		Schema: schemaTeamPermission,
		Codecs: map[resource.KindEncoding]resource.Codec{
			resource.KindEncodingJSON: &TeamPermissionJSONCodec{},
		},
	}
)

// Kind returns a resource.Kind for this Schema with a JSON codec
func TeamPermissionKind() resource.Kind {
	return kindTeamPermission
}

// Schema returns a resource.SimpleSchema representation of TeamPermission
func TeamPermissionSchema() *resource.SimpleSchema {
	return schemaTeamPermission
}

// Interface compliance checks
var _ resource.Schema = kindTeamPermission
