//
// Code generated by grafana-app-sdk. DO NOT EDIT.
//

package v0alpha1

import (
	"github.com/grafana/grafana-app-sdk/resource"
)

// schema is unexported to prevent accidental overwrites
var (
	schemaTeamMember = resource.NewSimpleSchema("iam.grafana.app", "v0alpha1", &TeamMember{}, &TeamMemberList{}, resource.WithKind("TeamMember"),
		resource.WithPlural("teammembers"), resource.WithScope(resource.NamespacedScope))
	kindTeamMember = resource.Kind{
		Schema: schemaTeamMember,
		Codecs: map[resource.KindEncoding]resource.Codec{
			resource.KindEncodingJSON: &TeamMemberJSONCodec{},
		},
	}
)

// Kind returns a resource.Kind for this Schema with a JSON codec
func TeamMemberKind() resource.Kind {
	return kindTeamMember
}

// Schema returns a resource.SimpleSchema representation of TeamMember
func TeamMemberSchema() *resource.SimpleSchema {
	return schemaTeamMember
}

// Interface compliance checks
var _ resource.Schema = kindTeamMember
